REGEX_REPLACE(
UK&
IF({Flow}="pre",
Part&"_"&
Chapter&"_"&
Heading&"_"&
{Section||Regulation}&"_"&
{Sub_Section||Sub_Regulation}&"_"&
Paragraph&"_"&
Sub_Paragraph&"_")&
IF(OR(Flow="",Flow="main"),"_"&
Part&"_"&
Chapter&"_"&
Heading&"_"&
{Section||Regulation}&"_"&
{Sub_Section||Sub_Regulation}&"_"&
Paragraph&"_"&
Sub_Paragraph&"_")&
IF(Flow="post","-")&
IF(REGEX_MATCH(Flow, "1|2|3|4|5|6|7|8|9|0"),"-"&Flow&"_"&
Part&"_"&
Chapter&"_"&
Heading&"_"&
{Section||Regulation}&"_"&
{Sub_Section||Sub_Regulation}&"_"&
Paragraph&"_"&
Sub_Paragraph&"_"),
"_*$",
"")&
IF(Record_Type="amendment","_a")