defmodule Types.AirtableSchema do
  @moduledoc false
  @type t :: %__MODULE__{
          country: :atom,
          title_name: String.t(),
          part: String.t(),
          part_name: String.t(),
          chapter: String.t(),
          chapter_name: String.t(),
          section: String.t(),
          section_name: String.t(),
          heading: String.t(),
          heading_name: String.t(),
          article: String.t(),
          article_name: String.t(),
          sub_article: String.t(),
          sub_article_name: String.t(),
          para: String.t(),
          para_name: String.t(),
          sub: String.t(),
          sub_name: String.t(),
          annex: String.t(),
          annex_name: String.t(),
          amendment: String.t(),
          amendment_name: String.t(),
          amending_sub_article_name: String.t(),
          form: String.t(),
          form_name: String.t(),
          approval_name: Strig.t()
        }
  @enforce_keys [:article, :article_name]
  defstruct country: nil,
            title_name: "title",
            part: "",
            part_name: "part",
            chapter: "",
            chapter_name: "chapter",
            section: "",
            section_name: "section",
            heading: "",
            heading_name: "heading",
            article: "",
            article_name: "article",
            sub_article: "",
            sub_article_name: "sub-article",
            para: ~s/^(\\d+)[ ](.*)/,
            para_name: "article, paragraph",
            sub: ~s/^(\\d+)_(\\d+)_(\\d+)[ ](.*)/,
            sub_name: "article, paragraph, sub-paragraph",
            annex: "",
            annex_name: "",
            amendment: "",
            amendment_name: "",
            amending_sub_article_name: "",
            form: "",
            form_name: "form",
            approval_name: "approval",
            table: ~s/^(\\d+)[ ](.*)/,
            table_name: "table"
end
