defmodule Types.AirtableSchema do
  @moduledoc false

  @fields [
    :flow,
    :type,
    :part,
    :chapter,
    :section,
    :article,
    :para,
    :sub,
    :text
  ]

  @number_fields [
    :part,
    :chapter,
    :section,
    :article,
    :para,
    :sub
  ]

  @type t :: %__MODULE__{
          country: :atom,
          fields: [],
          number_fields: [],
          title_name: String.t(),
          part: String.t(),
          part_name: String.t(),
          chapter: String.t(),
          chapter_name: String.t(),
          section: String.t(),
          section_name: String.t(),
          sub_section: String.t(),
          sub_section_name: String.t(),
          heading: String.t(),
          heading_name: String.t(),
          article: String.t(),
          article_name: String.t(),
          sub_article: String.t(),
          sub_article_name: String.t(),
          para: String.t(),
          para_name: String.t(),
          sub: String.t(),
          sub_name: String.t(),
          annex: String.t(),
          annex_name: String.t(),
          amendment: String.t(),
          amendment_name: String.t(),
          amending_sub_article_name: String.t(),
          form: String.t(),
          form_name: String.t(),
          approval_name: String.t(),
          note: String.t(),
          note_name: String.t(),
          footnote_name: String.t(),
          signed_name: String.t()
        }
  @enforce_keys [:article, :article_name]
  defstruct country: nil,
            fields: @fields,
            number_fields: @number_fields,
            title_name: "title",
            part: ~s/^(\\d+)[ ](.*)/,
            part_name: "part",
            chapter: ~s/^(\\d+)[ ](.*)/,
            chapter_name: "chapter",
            section: "",
            section_name: "section",
            sub_section: ~s/^(\\d+)[ ](.*)/,
            sub_section_name: "sub-section",
            heading: "",
            heading_name: "heading",
            article: "",
            article_name: "article",
            sub_article: "",
            sub_article_name: "sub-article",
            para: ~s/^(\\d+)[ ](.*)/,
            para_name: "article, paragraph",
            sub: ~s/^(\\d+)_(\\d+)_(\\d+)[ ](.*)/,
            sub_name: "article, paragraph, sub-paragraph",
            annex: ~s/(\\d*)[ ](.*)/,
            annex_name: "",
            amendment: "",
            amendment_name: "",
            amending_sub_article_name: "",
            form: "",
            form_name: "form",
            approval_name: "approval",
            table: ~s/^(\\d+)[ ](.*)/,
            table_name: "table",
            note: ~s/[ ](.*)/,
            note_name: "note",
            footnote_name: "footnote",
            signed_name: "signed"
end
