RU&
IF(
  OR(flow="",flow="main"),
  IF(part,"_"&part)&
  IF(section,"_"&section)&
  IF(chapter,"_"&chapter)&
  IF(article,"_"&article)&
  IF(para,"_"&para)&
  IF({sub},"_"&{sub})&
  IF({____X_},"_"&{____X_})
)&
IF(
  {flow}="pre",
  "__"&{Article Type}
)&
IF(
  {flow}="prov",
  "+"&
  IF(part,part&"_")&
  IF(article,article&"_")&
  IF(para,para&"_")&
  IF({sub},{sub}&"_")&
  IF({____X_},{____X_}&"_")
)&
IF(
  {flow}="post",
  "-"&
  IF(part,part&"_")&
  IF(section,section&"_")&
  IF(chapter,chapter&"_")&
  IF(article,article&"_")&
  IF(para,para&"_")&
  IF({sub},{sub}&"_")&
  IF({____X_},{____X_}&"_")
)&
IF(
  AND({flow}!="", {flow}!="main", {flow}!="pre", {flow}!="prov", {flow}!="post"),
  "-"&{flow}&
  IF(part,"_"&part)&
  IF(section,"_"&section)&
  IF(chapter,"_"&chapter)&
  IF(article,"_"&article)&
  IF(para,"_"&para)&
  IF({sub},"_"&{sub})&
  IF({____X_},"_"&{____X_})
)
